# Generated by Django 3.1.2 on 2021-02-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='author_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
