# Generated by Django 3.1.2 on 2021-02-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
